### PR TITLE
Updated host URL for wallet app

### PR DESCRIPTION
**Pull request by oleksandrsarapulovgl**

### CODE REVIEW

**Review by MykhailoNester — APPROVED** [review]

**Comment by yspreen** [comment]
Why is the URL hardcoded? That should **not** be the case. We have a context file for a reason @MykhailoNester @oleksandrsarapulovgl

**Review by ascheibal — CHANGES_REQUESTED** [review]
Please use the [wallet-context.jsonc](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/blob/main/app/src/main/assets/wallet-context.jsonc) as for cert pinning we have to use it also.

**Comment by oleksandrsarapulovgl** [comment]
> Why is the URL hardcoded? That should **not** be the case. We have a context file for a reason @MykhailoNester @oleksandrsarapulovgl

Because it make sense, and there was no related requirement - that HOST url might be floating. I'll open the issue for that and implement it

**Comment by oleksandrsarapulovgl** [comment]
> Please use the [wallet-context.jsonc](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/blob/main/app/src/main/assets/wallet-context.jsonc) as for cert pinning we have to use it also.

It's not so quick task to implement. Let's merge this, and I'll implement dynamic host fetching in scope of: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/40

?

**Comment by oleksandrsarapulovgl** [comment]
@ascheibal I updated logic to use dynamic urls for requests. Could you please review once again?

**Review by ascheibal — APPROVED** [review]

**Pull request merged**
